module.exports = {
  extends: [
    'tslint-clean-code',
    'tslint-eslint-rules',
    'tslint-sonarts'
  ],
  rulesDirectory: [
    'tslint-microsoft-contrib',
    'tslint-consistent-codestyle'
  ],
  rules: {
    'adjacent-overload-signatures': true,
    'member-ordering': [
      true,
      {
        alphabetize: false,
        order: [
          'public-static-field',
          'protected-static-field',
          'private-static-field',
          'public-instance-field',
          'protected-instance-field',
          'private-instance-field',
          'public-constructor',
          'protected-constructor',
          'private-constructor',
          'public-static-method',
          'protected-static-method',
          'private-static-method',
          'public-instance-method',
          'protected-instance-method',
          'private-instance-method'
        ]
      }
    ],
    'no-inferrable-types': true,
    'no-internal-module': true,
    'no-namespace': true,
    'no-non-null-assertion': true,
    'no-parameter-reassignment': true,
    'no-reference': true,
    'no-unnecessary-type-assertion': true,
    'no-var-requires': true,
    'only-arrow-functions': [true, 'allow-declarations', 'allow-named-functions'],
    'prefer-for-of': true,
    'unified-signatures': true,
    'await-promise': [true, 'Thenable'],
    'ban-comma-operator': true,
    curly: [true, 'ignore-same-line'],
    forin: true,
    'label-position': true,
    'no-arg': true,
    'no-bitwise': false,
    'no-conditional-assignment': true,
    'no-console': true,
    'no-construct': true,
    'no-debugger': true,
    'no-duplicate-super': true,
    'no-duplicate-switch-case': true,
    'no-duplicate-variable': true,
    'no-empty': true,
    'no-eval': true,
    'no-for-in-array': true,
    'no-inferred-empty-object-type': true,
    'no-invalid-template-strings': true,
    'no-invalid-this': true,
    'no-misused-new': true,
    'no-null-keyword': false,
    'no-return-await': true,
    'no-sparse-arrays': true,
    'no-string-literal': true,
    'no-string-throw': true,
    'no-this-assignment': [true, { 'allow-destructuring': true }],
    'no-unbound-method': [true, 'ignore-static'],
    'no-unsafe-finally': true,
    'no-unused-variable': true,
    'no-use-before-declare': true,
    'no-var-keyword': true,
    'prefer-object-spread': true,
    radix: true,
    'restrict-plus-operands': true,
    // 'strict-boolean-expressions': [true, 'allow-null-union', 'allow-undefined-union']
    'strict-type-predicates': true,
    'use-default-type-parameter': true,
    'use-isnan': true,
    'cyclomatic-complexity': [true, 10],
    deprecation: true,
    eofline: true,
    indent: [true, 'spaces', 2],
    'linebreak-style': [true, 'LF'],
    'max-line-length': [true, { limit: 120, 'ignore-pattern': 'expect|^assert{(.*?)}' }],
    'no-duplicate-imports': true,
    'no-require-imports': true,
    'prefer-const': [true, { destructuring: 'all' }],
    'trailing-comma': [true, { multiline: 'never', singleline: 'never' }],
    align: [true, 'parameters', 'arguments', 'statements', 'members', 'elements'],
    'array-type': [true, 'array'],
    'arrow-parens': [true, 'ban-single-arg-parens'],
    'arrow-return-shorthand': true,
    'binary-expression-operand-order': true,
    'callable-types': true,
    'class-name': true,
    'comment-format': [true, 'check-space'],
    encoding: true,
    'import-spacing': true,
    'interface-name': [true, 'never-prefix'],
    'interface-over-type-literal': true,
    'new-parens': true,
    'no-angle-bracket-type-assertion': true,
    'no-boolean-literal-compare': true,
    'no-consecutive-blank-lines': true,
    'no-irregular-whitespace': true,
    // no-parameter-properties
    'no-redundant-jsdoc': true,
    // no-reference-import
    'no-trailing-whitespace': true,
    'no-unnecessary-callback-wrapper': true,
    'no-unnecessary-initializer': true,
    'no-unnecessary-qualifier': true,
    'number-literal-format': true,
    'object-literal-key-quotes': [true, 'as-needed'],
    'object-literal-shorthand': true,
    'one-line': [true, 'check-catch', 'check-finally', 'check-else', 'check-open-brace', 'check-whitespace'],
    'prefer-method-signature': true,
    'prefer-switch': false,
    'prefer-template': true,
    quotemark: [true, 'single', 'jsx-single', 'avoid-escape', 'avoid-template'],
    semicolon: [true, 'never'],
    'space-before-function-paren': [true, 'always'],
    'space-within-parens': [true, 0],
    'switch-final-break': [true, 'always'],
    'variable-name': [true, 'check-format'],
    whitespace: [
      true,
      'check-branch',
      'check-decl',
      'check-operator',
      'check-module',
      'check-separator',
      'check-rest-spread',
      'check-type',
      'check-typecast',
      'check-type-operator',
      'check-preblock'
    ],
    'no-document-write': true,
    'no-exec-script': true,
    'no-function-constructor-with-string-args': true,
    'no-invalid-regexp': true,
    'no-string-based-set-immediate': true,
    'no-string-based-set-interval': true,
    'no-string-based-set-timeout': true,
    'no-typeof-undefined': true,
    'no-unnecessary-bind': true,
    'no-unnecessary-field-initialization': true,
    'no-unnecessary-local-variable': true,
    'no-unnecessary-override': true,
    'no-unnecessary-semicolons': true,
    'non-literal-require': true,
    'prefer-array-literal': true,
    'no-ex-assign': true,
    'no-extra-semi': true,
    'no-inner-declarations': false,
    'no-unexpected-multiline': true,
    'no-reserved-keywords': false,
    'no-implicit-dependencies': false,
    'no-relative-imports': false,
    typedef: false,
    // typedef-whitespace
    'missing-jsdoc': false,
    'object-curly-spacing': [true, 'always'],
    'no-accessor-recursion': true,
    'no-collapsible-if': true,
    'no-unnecessary-else': true,
    'no-unnecessary-type-annotation': true,
    'no-unused': true,
    'max-func-args': [true, 6],
    'no-flag-args': true,
    'no-case-with-or': true,
    'no-collection-size-mischeck': true,
    'no-empty-destructuring': true,
    'no-identical-conditions': true,
    'no-identical-expressions': true,
    'no-misspelled-operator': true,
    'no-self-assignment': true,
    'no-dead-store': true,
    'no-redundant-boolean': true,
    'no-same-line-conditional': true,
    'prefer-immediate-return': true,
    'cognitive-complexity': false,
    'mccabe-complexity': false,
    'no-accessor-field-mismatch': false,
    'no-all-duplicated-branches': false,
    'no-array-delete': false,
    'no-big-function': false,
    'no-commented-code': false,
    'no-duplicate-string': false,
    'no-duplicated-branches': false,
    'no-element-overwrite': false,
    'no-empty-nested-blocks': false,
    'no-extra-semicolon': false,
    'no-gratuitous-expressions': false,
    'no-hardcoded-credentials': false,
    'no-identical-functions': false,
    'no-ignored-initial-value': false,
    'no-ignored-return': false,
    'no-inconsistent-return': false,
    'no-misleading-array-reverse': false,
    'no-multiline-string-literals': false,
    'no-nested-incdec': false,
    'no-redundant-parentheses': false,
    'no-return-type-any': false,
    'no-small-switch': false,
    'no-statements-same-line': false,
    'no-unconditional-jump': false,
    'no-unenclosed-multiline-block': false,
    'no-unthrown-error': false,
    'no-unused-array': false,
    'no-use-of-empty-return-value': false,
    'no-useless-cast': false,
    'no-useless-increment': false,
    'no-useless-intersection': false,
    'no-variable-usage-before-declaration': false,
    'parameters-max-number': false,
    'use-primitive-type': false,
    'use-type-alias': false
  }
}
