const standard = require('./standard')

module.exports = {
  extends: [
    'tslint-clean-code',
    'tslint-eslint-rules',
    'tslint-sonarts'
  ],
  rulesDirectory: [
    'tslint-microsoft-contrib',
    'tslint-consistent-codestyle'
  ],
  rules: {
    ...standard.rules,
    'member-access': [true, 'check-accessor', 'check-constructor', 'check-parameter-property'],
    'no-any': false,
    'no-empty-interface': true,
    'no-dynamic-delete': true,
    'no-import-side-effect': [
      true,
      { 'ignore-module': '(\\.css|\\.scss|\\.sass|\\.less|\\.styl|\\.html|\\.pug|\\.vue)$' }
    ],
    'no-magic-numbers': [true, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -0, -1, -2, -3, -4, -5, -6, -7, -8, -9, -10],
    'promise-function-async': true,
    'no-floating-promises': true,
    'no-object-literal-type-assertion': true,
    'no-shadowed-variable': true,
    'no-switch-case-fall-through': true,
    'no-unsafe-any': false,
    'no-unused-expression': true,
    // no-void-expression
    'object-literal-sort-keys': false,
    'prefer-conditional-expression': true,
    'switch-default': true,
    'triple-equals': true,
    'cyclomatic-complexity': [true, 5],
    'max-classes-per-file': [true, 1, 'exclude-class-expressions'],
    // max-file-line-count
    // no-default-export
    'no-mergeable-namespace': true,
    'prefer-const': [true, { destructuring: 'any' }],
    'prefer-readonly': true,
    // completed-docs
    'newline-before-return': true,
    'one-variable-per-declaration': [true, 'ignore-for-loop'],
    'ordered-imports': [true, { 'import-sources-order': 'lowercase-last', 'named-imports-order': 'lowercase-last' }],
    'return-undefined': true,
    'export-name': true,
    'chai-prefer-contains-to-index-of': true,
    'chai-vague-errors': true,
    'function-name': [ true, {
      "method-regex": "^[?[\w\d.]+]?$",
      "private-method-regex": "^[?[\w\d.]+]?$",
      "protected-method-regex": "^[?[\w\d.]+]?$",
      "static-method-regex": "^[?[\w\d.]+]?$",
      "function-regex": "^[a-z][\w\d]+$"
    }],
    'import-name': true,
    'insecure-random': true,
    'jquery-deferred-must-complete': true,
    'max-func-body-length': [
      true,
      15,
      {
        'arrow-body-length': 10,
        'ctor-body-length': 15,
        'func-body-length': 15,
        'func-expression-body-length': 15,
        'ignore-comments': true,
        // tslint:disable:max-line-length
        'ignore-parameters-to-function-regex': '(describe|context|it|specify|before|after|beforeEach|afterEach|suite|test|suiteSetup|suiteTeardown|setup|teardown)',
        'method-body-length': 15
      }
    ],
    'missing-jsdoc': true,
    'mocha-avoid-only': true,
    'mocha-no-side-effect-code': true,
    'mocha-unneeded-done': true,
    'no-banned-terms': true,
    'no-constant-condition': true,
    'no-control-regex': true,
    'no-empty-line-after-opening-brace': true,
    'no-increment-decrement': true,
    'no-multiline-string': true,
    'no-octal-literal': true,
    'no-regex-spaces': true,
    'no-useless-files': true,
    'no-with-statement': true,
    'possible-timing-attack': true,
    'promise-must-complete': true,
    'no-empty-character-class': true,
    'no-extra-boolean-cast': true,
    'valid-jsdoc': false,
    'no-relative-imports': true,
    'early-exit': [true, { 'max-length': 1 }],
    'strict-type-predicates': true,
    'prefer-while': true,
    'max-func-args': [true, 4],
    'no-flag-args': true,
    'newspaper-order': false,
    'min-class-cohesion': [true, 0.5],
    'no-for-each-push': true,
    'no-feature-envy': [true, 1, ['_']],
    'no-map-without-usage': true,
    'no-complex-conditionals': true,
    'prefer-dry-conditionals': true,
    'no-commented-out-code': true,
    'no-all-duplicated-branches': true,
    'no-element-overwrite': true,
    'no-ignored-initial-value': true,
    'no-ignored-return': true,
    'no-misleading-array-reverse': true,
    'no-unthrown-error': true,
    'no-use-of-empty-return-value': true,
    'no-useless-increment': true,
    'no-useless-intersection': true,
    'cognitive-complexity': [true, 5],
    'no-accessor-field-mismatch': true,
    'no-array-delete': true,
    'no-duplicate-string': [true, 2],
    'no-duplicated-branches': true,
    'no-gratuitous-expressions': true,
    'no-hardcoded-credentials': true,
    'no-identical-functions': true,
    'no-redundant-parentheses': true,
    'no-small-switch': true,
    'no-statements-same-line': true,
    'no-unconditional-jump': true,
    'no-unused-array': true
  }
}
